AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master template para nested stacks con Docker desde S3'

Parameters:
  ProjectName:
    Type: String
    Default: 'aws-ha-webapp'
  DBUsername:
    Type: String
    Default: 'admin'
  DBPassword:
    Type: String
    NoEcho: true
  DockerImage:
    Type: String
    Description: 'URI de la imagen Docker en ECR o Docker Hub'
    Default: 'nginx:latest'
  TemplatesBucket:
    Type: String
    Description: 'Bucket S3 donde estan los templates'

Resources:
  # VPC y Networking
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/vpc.yaml'
      Parameters:
        ProjectName: !Ref ProjectName

  # Base de datos RDS (primero)
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/database.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  # Fargate Compute Stack
  FargateStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DatabaseStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/fargate-docker.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        DBEndpoint: !GetAtt DatabaseStack.Outputs.DBEndpoint
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DockerImage: !Ref DockerImage

Outputs:
  ApplicationURL:
    Description: 'URL de la aplicacion web'
    Value: !Sub 'http://${FargateStack.Outputs.LoadBalancerDNS}'
  
  DatabaseEndpoint:
    Description: 'Endpoint de la base de datos RDS'
    Value: !GetAtt DatabaseStack.Outputs.DBEndpoint

  ECSCluster:
    Description: 'ECS Cluster'
    Value: !GetAtt FargateStack.Outputs.ECSCluster